add helpers to image-test

diff --git a/bin/test-image b/bin/test-image
--- a/bin/test-image
+++ b/bin/test-image
@@ -2,7 +2,66 @@
 set -eu
 
 # Source helpers script.
-. "$(dirname "${0}")/helpers"
+#. "$(dirname "${0}")/helpers"
+
+#
+# Helpers.
+#
+
+# waitInstanceReady: waits for the instance to be ready (processes count > 1).
+waitInstanceReady() (
+  set +x
+  maxWait=90
+  instName="${1}"
+  instProj="${2:-}"
+  if [ -z "${instProj}" ]; then
+    # Find the currently selected project.
+    instProj="$(lxc project list -f csv | sed -n 's/^\([^(]\+\) (current),.*/\1/ p')"
+  fi
+
+  # Wait for the instance to report more than one process.
+  processes=0
+  for _ in $(seq "${maxWait}"); do
+      processes="$(lxc info --project "${instProj}" "${instName}" | awk '{if ($1 == "Processes:") print $2}')"
+      if [ "${processes}" -gt 1 ]; then
+          return 0 # Success.
+      fi
+      sleep 1
+  done
+
+  echo "Instance ${instName} (${instProj}) not ready after ${maxWait}s"
+  return 1 # Failed.
+)
+
+# waitInstanceBooted: waits for the instance to be ready and fully booted.
+waitInstanceBooted() (
+  set +x
+  maxWait=90
+  instName="$1"
+  instProj="${2:-}"
+  if [ -z "${instProj}" ]; then
+    # Find the currently selected project.
+    instProj="$(lxc project list -f csv | sed -n 's/^\([^(]\+\) (current),.*/\1/ p')"
+  fi
+
+  # Wait for the instance to be ready
+  waitInstanceReady "${instName}" "${instProj}"
+
+  # Then wait for the boot sequence to complete.
+  sleep 1
+  state="$(lxc exec --project "${instProj}" "${instName}" -- timeout "${maxWait}" systemctl is-system-running --wait || true)"
+  if [ "${state}" = "running" ]; then
+    return 0 # Success.
+  fi
+
+  echo "Instance ${instName} (${instProj}) not booted after ${maxWait}s"
+  lxc list --project "${instProj}" "${instName}"
+  return 1 # Failed.
+)
+
+#
+# Validation and setup.
+#
 
 # Check input arguments.
 if [ "${1:-}" = "" ] || [ "${2:-}" = "" ] || [ "${3:-}" = "" ] || [ "${4:-}" = "" ] || [ "${5:-}" = "" ]; then
@@ -163,8 +222,12 @@ done
 
 lxc list "${TEST_IMAGE}"
 
+#
+# Tests.
+#
+
 # Check that all instances have an IPv4 and IPv6 address.
-echo "==> Performing network tests"
+echo "==> Performing tests"
 FAIL=0
 for url in $(lxc query "/1.0/instances" | jq -r .[] | grep "${TEST_IMAGE}"); do
     name=$(echo "${url}" | cut -d/ -f4)
