tests/conversion
Signed-off-by: Din Music <din.music@canonical.com>

diff --git a/tests/conversion b/tests/conversion
--- a/tests/conversion
+++ b/tests/conversion
@@ -131,7 +131,7 @@ installVirtV2V(){
 # 1: Name of new virtual machine.
 # 2: Type of the storage pool.
 # 3: Path to the image.
-# 4: UEFI secure boot (yes/no).
+# 4: Security mode (secureboot/csm/none).
 # 5: Conversion options.
 conversion_vm() {
     conversion vm "$1" "$2" "$3" "$4" "${5:-format}"
@@ -153,7 +153,7 @@ conversion() {
     instName=$2
     poolType=$3
     imgPath=$4
-    uefi_sb=$5
+    secMode=$5
     conversionOptions=$6
 
     if [ "${instType}" = "vm" ]; then
@@ -219,11 +219,8 @@ conversion() {
         echo "${instName}"     # Instance name.
         echo "${imgPath}"      # Local image path (or filesystem path in case of container).
 
-        if [ "${uefi_sb}" = "yes" ]; then
-            echo "${uefi_sb}"  # Enable UEFI secure boot.
-        else
-            echo "no"
-        fi
+        # Enable UEFI secure boot.
+        [ "${secMode}" = "secureboot" ] && echo "yes" || echo "no"
 
         # Configure storage pool.
         if [ "${poolName}" != "" ]; then
@@ -233,10 +230,8 @@ conversion() {
             echo "10GiB"       # Pool size.
         fi
 
-        if [ "${uefi_sb}" = "csm" ]; then
-            echo "3"           # Set config option.
-            echo "security.csm=true"
-        fi
+        # Set instance config options.
+        [ "${secMode}" = "csm" ] && echo "3" && echo "security.csm=true"
 
         # Begin the migration with the above configuration
         sleep 1
@@ -279,8 +274,11 @@ EOF
     echo "Check network connectivity of instance ${instName}..."
     checkIPAddresses "${instName}"
 
-    echo "Check DNS resolution of instance ${instName}..."
-    checkDNS "${instName}"
+    # We cannot install lxd-agent using cloud-init on CentOS 7 image.
+    if [ "${secMode}" != "csm" ]; then
+        echo "Check DNS resolution of instance ${instName}..."
+        checkDNS "${instName}"
+    fi
 
     # Cleanup.
     lxc delete -f "${instName}"
@@ -314,7 +312,7 @@ tmpdir="$(mktemp -d)"
 # Test VM migration using conversion mode. If server does not support
 # conversion API extension, lxd-migrate must fallback to migration
 # mode and successfully transfer the VM disk.
-# conversion_vm vm-alpine-raw-zfs zfs "${tmpdir}/backup/virtual-machine.img" "no"
+# conversion_vm vm-alpine-raw-zfs zfs "${tmpdir}/backup/virtual-machine.img" "none"
 # rm -rf "${tmpdir}/backup"
 
 # Test VM conversion using non-raw disk formats only if server supports
@@ -324,84 +322,40 @@ if hasNeededAPIExtension instance_import_conversion; then
     IMAGE_PATH="${tmpdir}/image"
 
     # lxc image export images:alpine/edge "${IMAGE_PATH}" --vm
-    # conversion_vm vm-alpine-qcow2-zfs zfs "${IMAGE_PATH}.root" "no"
+    # conversion_vm vm-alpine-qcow2-zfs zfs "${IMAGE_PATH}.root" "none"
 
     # lxc image export images:centos/9-Stream "${IMAGE_PATH}" --vm
-    # conversion_vm vm-centos9-qcow2-btrfs btrfs "${IMAGE_PATH}.root" "yes"
+    # conversion_vm vm-centos9-qcow2-btrfs btrfs "${IMAGE_PATH}.root" "secureboot"
 
     # rm "${IMAGE_PATH}" "${IMAGE_PATH}.root"
 
     # Test VMDK image.
     # wget -q -O "${IMAGE_PATH}" https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.vmdk
 
-    # conversion_vm vm-u24-vmdk-dir dir "${IMAGE_PATH}" "yes"
-    # conversion_vm vm-u24-vmdk-zfs zfs "${IMAGE_PATH}" "yes"
+    # conversion_vm vm-u24-vmdk-dir dir "${IMAGE_PATH}" "secureboot"
+    # conversion_vm vm-u24-vmdk-zfs zfs "${IMAGE_PATH}" "secureboot"
 
     # Use custom volume for backups. Images for conversion will be uploaded here.
     # lxc storage create backups-pool zfs
     # lxc storage volume create backups-pool backups-vol
     # lxc config set storage.backups_volume=backups-pool/backups-vol
 
-    # conversion_vm vm-u24-vmdk-dir-bupvol dir "${IMAGE_PATH}" "yes"
-    # conversion_vm vm-u24-vmdk-zfs-bupvol zfs "${IMAGE_PATH}" "yes"
+    # conversion_vm vm-u24-vmdk-dir-bupvol dir "${IMAGE_PATH}" "secureboot"
+    # conversion_vm vm-u24-vmdk-zfs-bupvol zfs "${IMAGE_PATH}" "secureboot"
 
     # rm "${IMAGE_PATH}"
 
+    # Test virtio conversion if virt-v2v-in-place is installed and meets the minimum version
+    # requirements. Version will be satisfied from Ubuntu 24.04 runners onwards.
+    v2vMinVersion="2.3.4"
     if ! command -v virt-v2v-in-place > /dev/null; then
-        installVirtV2V "v2.4.0"
-    fi
-
-    # Test virtio conversion if virt-v2v-in-place meets minimum version requirements.
-    # Version will be satisfied from Ubuntu 24.04 runners onwards.
-    v2vVersion=$(virt-v2v-in-place --version | grep -oP '\d+\.\d+\.\d+')
-    minVersion="2.3.4"
-
-    if dpkg --compare-versions "${v2vVersion}" "ge" "${minVersion}"; then
-        wget -q -O "${IMAGE_PATH}" https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
-
-        # MOUNT_POINT=$(mktemp -d /mnt/tmp.XXXXXXX)
-
-        # Mount the image and install cloud-init.
-#         guestmount -a "${IMAGE_PATH}" -m /dev/sda1 "${MOUNT_POINT}"
-
-#         mount --bind /dev "$MOUNT_POINT/dev"
-#         mount --bind /proc "$MOUNT_POINT/proc"
-#         mount --bind /sys "$MOUNT_POINT/sys"
-#         mount --bind /run "$MOUNT_POINT/run"
-
-#         chroot "${MOUNT_POINT}" <<'EOF'
-# yum clean all
-# yum makecache
-# yum install -y epel-release
-# yum install -y cloud-init
-# EOF
-
-#         umount "$MOUNT_POINT/dev"
-#         umount "$MOUNT_POINT/proc"
-#         umount "$MOUNT_POINT/sys"
-#         umount "$MOUNT_POINT/run"
-#         umount "$MOUNT_POINT"
-#         guestunmount "${MOUNT_POINT}"
-
-
-        # modprobe nbd max_part=8
-        # qemu-nbd --connect=/dev/nbd0 "${IMAGE_PATH}"
-        # fdisk -l /dev/nbd0
-
-        # mount /dev/nbd0p1 /mnt/mydisk
-
-        # .. do something with /mnt/mydisk ...
-
-        # umount /mnt/mydisk
-
-        # qemu-nbd --disconnect /dev/nbd0
-
-
-
-        # Run conversion with driver injection.
-        conversion_vm vm-centos7-qcow2-zfs-bupvol dir "${IMAGE_PATH}" "csm" "format,virtio"
+        echo "===> SKIP: The virt-v2v-in-place cannot be installed on the runner"
+    elif dpkg --compare-versions "$(virt-v2v-in-place --version | grep -oP '\d+\.\d+\.\d+')" "ge" "${v2vMinVersion}"; then
+        echo "===> SKIP: The virt-v2v-in-place version is lower then minimum required version ${v2vMinVersion}"
     else
-        echo "===> SKIP: The virt-v2v-in-place version ${v2vVersion} is lower then minimum required version ${minVersion}"
+        # Run conversion with driver injection on centos7 image.
+        wget -q -O "${IMAGE_PATH}" https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
+        conversion_vm vm-centos7-qcow2-zfs-bupvol dir "${IMAGE_PATH}" "csm" "format,virtio"
     fi
 
     # Cleanup.
